project:
  type: book
  output-dir: docs
  execute-dir: project
  resources:
  - "data/wildfire/whp_raw_sample.csv"

book:
  title: "Goal, Code, Verify, Reflect"
  subtitle: "Guided Activities for Learning R Workflow"
  author: "Lorraine Gaudio"
  search: true
  chapters:
    - index.qmd
    - front-matter/preface.qmd
      chapters:
        - "Core Module 1 Tenacity/@Preface.Rmd"
        - "Core Module 1 Tenacity/PUT-EXACT-CHAPTER-1-FILENAME-HERE.Rmd"
        - "Core Module 1 Tenacity/PUT-EXACT-CHAPTER-2-FILENAME-HERE.Rmd"
        
  appendices:
    - back-matter/glossary.Rmd

format:
  html:
    theme: cosmo
    css: styles/guided-book.css
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto